Join users and union members
profcomff/dwh-pipelines pull request #145
Opened 2024-12-07 16:27 UTC by Wudext

2024-12-07 16:30 UTC, Zimovchik approved these changes

2024-12-07 16:35 UTC, parfenovma requested changes

2024-12-07 16:35 UTC, parfenovma commented on pipelines/dm/userdata/__init__.py
> +            t1.full_name = t2.full_name;
а смотрел сколько приджойнилось? мы смотрели что лучше по имейлу, больше будет совпадений

2024-12-07 18:28 UTC, Wudext commented on pipelines/dm/userdata/__init__.py
> +            t1.full_name = t2.full_name;
А в "DWH_USER".union_member нет email, там только фио

2024-12-07 18:34 UTC, parfenovma requested changes

2024-12-07 18:34 UTC, parfenovma commented on pipelines/dm/userdata/__init__.py
> +            t1.full_name = t2.full_name;
```sql
select 
 userdata.user_id as userdata_user_id,
 userdata.full_name as full_name,
 um.first_name as first_name,
 um.last_name as last_name,
 um.type_of_learning as type_of_learning,
 um.rzd_status as wtf_value,
 um.academic_level as academic_level,
 um.rzd_number as rzd_number,
 um.card_id as card_id,
 um.card_number as card_number
from 
 (SELECT 
  STRING_TO_ARRAY(email, ',') as email_list,
  user_id,
  full_name
 FROM "DWH_USER_INFO".info
 ) as userdata
join "STG_UNION_MEMBER".union_member as um
on um.email=any(userdata.email_list)```

2024-12-07 18:34 UTC, parfenovma commented on pipelines/dm/userdata/__init__.py
> +            t1.full_name = t2.full_name;
а update policy? он будет падать после первого запуска или перезатираться? или там инкремент будет?

2024-12-11 08:09 UTC, Wudext commented on pipelines/dm/userdata/__init__.py
> +            t1.full_name = t2.full_name;
Сделал апсерт

2024-12-11 08:13 UTC, parfenovma requested changes

2024-12-11 08:13 UTC, parfenovma commented on pipelines/dm/userdata/__init__.py
> +    tags=["dm", "src", "userdata"],
https://docs.profcomff.com/dwh/data_intellegence.html
сделай пожалуйста более понятный айдишник)

2024-12-11 08:13 UTC, parfenovma commented on pipelines/dm/userdata/__init__.py
> +    schedule="50 2 */1 * *",
давай запускаться по триггеру, у нас же есть dwh таблички
[пример](https://github.com/profcomff/dwh-pipelines/blob/main/pipelines/dwh/auth/info/__init__.py#L111)

2024-12-11 08:13 UTC, parfenovma commented on pipelines/dm/userdata/__init__.py
> +    sql_engine.execute(
коннекшен и штуки для работы с постгресом тоже есть в эирфлоу 
[пример](https://github.com/profcomff/dwh-pipelines/blob/main/pipelines/ods/auth/auth_method/__init__.py#L23)

2024-12-11 18:47 UTC, parfenovma approved these changes

2024-12-11 19:19 UTC, merged