#18
profcomff/dwh-pipelines pull request #22
Opened 2023-08-01 14:08 UTC by Wudext

## Изменения
Начал работу по улучшению/поддержанию репозитория

## Реализации
Пофиксил #18

## Детали
1) Поменял логику работы ТГ бота, сообщение отправляется только при ошибке 

## Check-List
- [x] Вы проверили свой код перед отправкой запроса?
- [А тут и не надо] Вы написали тесты к реализованным функциям?
- [x] Вы не забыли применить black и isort?

2023-09-18 09:17 UTC, dyakovri commented
Тут конфликов шо пипец
Непонятно, какие изменения были сделаны, описание вообще не объясняет

2024-03-01 11:14 UTC, Wudext commented
https://stackoverflow.com/questions/76365797/how-do-i-get-airflow-to-work-with-sqlalchemy-2-0-2-when-it-has-a-1-4-48-version

2024-03-08 18:18 UTC, grigoriev-semyon requested changes
Сначала надо резолвить конфликты, потом заново смотреть

2024-03-29 13:04 UTC, grigoriev-semyon commented on union_members/fetch.py
> +    on_failure_callback=send_telegram_message(-633287506),
вроде id чата неправильное

2024-03-29 13:18 UTC, grigoriev-semyon requested changes
надо откатить любые изменения форматирования либо сделать новый пр без них

2024-04-05 06:32 UTC, closed without merging