75 task
profcomff/dwh-pipelines pull request #77
Opened 2024-05-31 19:45 UTC by Wudext

2024-05-31 20:04 UTC, Wudext commented on dagtrans75
> +	insert into DM.infra_logs(id,message,container_name,create_ts) VALUES ({id[i]},{message[i]},{container_name[i]},{create_ts[i]})'''
DM_INFRA_LOGS а не просто DM
DM_INFRA_LOGS.incident скорее всего

2024-05-31 20:04 UTC, Wudext commented on dagtrans75
> +        using DM.infra_logs_Incident as ne,
DM_INFRA_LOGS.incident

2024-05-31 20:04 UTC, Wudext commented on dagtrans75
> +          insert into infra_logs_Incident values (e.id, e.message, e.container_name, e.create_ts)''')
DM_INFRA_LOGS.incident

2024-05-31 20:04 UTC, Wudext commented on dagtrans75
> +    def start():
@dag(
    schedule='0 */1 * * *',
    start_date=datetime(2024, 1, 1, 2, 0, 0),
    catchup=False,
    tags=["dwh"],
    default_args={"owner": "dwh", "retries": 3, "retry_delay": timedelta(minutes=5)}
)
def start():
  trans()

start()

2024-06-21 18:28 UTC, grigoriev-semyon requested changes

2024-06-21 18:28 UTC, grigoriev-semyon commented on dagtrans75.py
> +            insert into DM_INFRA_LOGS.incident(id,message,container_name,create_ts) VALUES ({id[i]},{message[i]},{container_name[i]},{create_ts[i]})''')
Зачем он тут? Его функции выполнит merge into

2024-06-21 18:28 UTC, grigoriev-semyon commented on dagtrans75.py
> +        on e.id = ne.id
Почему такой джойн? Айдишники меняются, он вроде вообще будет выдавать пустое множество всегда

2024-06-21 18:28 UTC, grigoriev-semyon commented on dagtrans75.py
> +        update set (e.create_ts = ne.create_ts) and (e.message = ne.message) and (e.container_name = ne.container_name) and (e.id = ne.id)
Зачем апдейт?

2024-06-21 19:30 UTC, SofyaFin commented on dagtrans75.py
> +        update set (e.create_ts = ne.create_ts) and (e.message = ne.message) and (e.container_name = ne.container_name) and (e.id = ne.id)
а в merge into разве не обязательно делать update?

2024-06-21 19:31 UTC, SofyaFin commented on dagtrans75.py
> +        on e.id = ne.id
хм, а тогда на основании чего мерджить? там вроде все меняется

2024-06-21 19:31 UTC, SofyaFin commented on dagtrans75.py
> +            insert into DM_INFRA_LOGS.incident(id,message,container_name,create_ts) VALUES ({id[i]},{message[i]},{container_name[i]},{create_ts[i]})''')
это поправлю

2024-06-21 20:05 UTC, SofyaFin commented on dagtrans75.py
> +        on e.id = ne.id
просто у нас получается, что таблица incident пока пустая и как-то странно мерджить ее

2024-06-21 20:09 UTC, grigoriev-semyon commented on dagtrans75.py
> +        on e.id = ne.id
container_name, message

2024-06-21 20:11 UTC, grigoriev-semyon commented on dagtrans75.py
> +        update set (e.create_ts = ne.create_ts) and (e.message = ne.message) and (e.container_name = ne.container_name) and (e.id = ne.id)
можно не делать

2024-06-21 20:12 UTC, SofyaFin commented on dagtrans75.py
> +        update set (e.create_ts = ne.create_ts) and (e.message = ne.message) and (e.container_name = ne.container_name) and (e.id = ne.id)
спасибо)

2024-06-21 20:29 UTC, grigoriev-semyon commented on dagtrans75.py
> +        on e.message = ne.message
не до конца сделан джойн

2024-06-21 20:29 UTC, grigoriev-semyon commented on dagtrans75.py
> +            create_ts[i] = res[i][3]
эта часть не используется

2024-06-21 20:29 UTC, grigoriev-semyon commented on dagtrans75.py
> +        merge into  ODS_INFRA_LOGS.container_log as e,
ты мерджишь все записи?

2024-06-21 20:30 UTC, SofyaFin commented on dagtrans75.py
> +        merge into  ODS_INFRA_LOGS.container_log as e,
получается, да

2024-07-03 12:55 UTC, closed without merging