75 task обновленная
profcomff/dwh-pipelines pull request #79
Opened 2024-07-03 13:00 UTC by SofyaFin

## Изменения

## Детали реализации

## Check-List

- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
-

2024-07-03 13:06 UTC, Wudext commented on dagtrans75.py
> +  id,
Тут табуляция съехала

Пропиши в консоли black dagtrans75.py

2024-07-03 13:06 UTC, Wudext commented on dagtrans75.py
Лучше скорее всего добавить этот файл в папку infra

2024-07-03 13:22 UTC, SofyaFin commented on dagtrans75.py
> +  id,
да

2024-07-03 13:23 UTC, SofyaFin commented on dagtrans75.py
да

2024-07-03 13:33 UTC, grigoriev-semyon requested changes

2024-07-03 13:33 UTC, grigoriev-semyon commented on infra/ods_to_dm_logs.py
> +    schedule="0 */1 * * *",
Почему по расписанию?

2024-07-03 13:33 UTC, grigoriev-semyon commented on infra/ods_to_dm_logs.py
> +    with dwh_sql_engine.connect() as conn:
Есть PostgresOperator для этого вроде, Рома им пользовался

2024-07-03 13:33 UTC, grigoriev-semyon commented on infra/ods_to_dm_logs.py
> +    start_date=datetime(2024, 1, 1, 2, 0, 0),
Зачем указывать секунды в дате?

2024-07-03 13:33 UTC, grigoriev-semyon commented on infra/ods_to_dm_logs.py
> +  id,
Зачем селектить id?

2024-07-03 13:33 UTC, grigoriev-semyon commented on infra/ods_to_dm_logs.py
Почему новый файл а не logs.py?

2024-07-03 13:33 UTC, grigoriev-semyon commented on infra/ods_to_dm_logs.py
> +        with sq as (select
Форматирование поехало

2024-07-03 13:44 UTC, SofyaFin commented on infra/ods_to_dm_logs.py
> +  id,
раньше я его использовала. снести его?

2024-07-03 13:44 UTC, SofyaFin commented on infra/ods_to_dm_logs.py
> +        with sq as (select
через black не правит

2024-07-03 13:44 UTC, SofyaFin commented on infra/ods_to_dm_logs.py
не совсем поняла

2024-07-05 12:52 UTC, grigoriev-semyon requested changes

2024-07-05 12:52 UTC, grigoriev-semyon commented on infra/logs.py
> +        schedule=[Dataset("DM_INFRA_LOGS.incident_hint")],
я даже не знаю как это прокомментировать по русски 
расписание в зависимости от самого себя?

2024-07-05 12:52 UTC, grigoriev-semyon commented on infra/ods_to_dm_logs.py
> +    trans()
зачем оставлять этот файл если ты все перенесла?

2024-07-05 12:52 UTC, grigoriev-semyon commented on infra/logs.py
> +    with sq as (select
форматирование неправильное
почему следующая строка левее первой?

2024-07-27 11:17 UTC, grigoriev-semyon requested changes

2024-07-27 11:17 UTC, grigoriev-semyon commented on infra/logs.py
> +        dag_id="trans_from_ODS_INFRA_LOGS.container_log_to_DM_INFRA_LOGS.incident_hint_infra_logs",
Тяжелое название какое то

2024-07-27 11:17 UTC, grigoriev-semyon commented on infra/logs.py
> +        task_id="trans_from_ODS_INFRA_LOGS.container_log_to_DM_INFRA_LOGS.incident_hint_infra_logs",
Название не очень

2024-08-03 07:38 UTC, grigoriev-semyon approved these changes

2024-08-03 07:41 UTC, merged