mymsufetch dag initial commit
profcomff/dwh-pipelines pull request #97
Opened 2024-08-18 07:14 UTC by Zimovchik

## Изменения

## Детали реализации

## Check-List

- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-08-18 08:35 UTC, Zimovchik commented
надо ответить на вопросы:

1. В каком формате полное имя препода
2. как поступаем с группами разделенными типо 201_1 и тд например для англа
3. как лучше это организовать: будем в даге одном сразу писать и flattenить или лучше отдельно
4. наверное лучше по команде сразу забирать на весь семестр без периодичности

2024-08-18 08:46 UTC, mixx3 reviewed
супер!)

2024-08-18 08:46 UTC, mixx3 commented on timetable/mymsuapi_fetch.py
> +        return None
вот тут requestException сложно получить, скоре надо обрабатывать когда response.status_code != 200 и падать с ошибкой

2024-08-18 08:46 UTC, mixx3 commented on timetable/mymsuapi_fetch.py
> +    values_to_keep = [
вот это сделай set() чтобы в 103 строчке усколить ` res.append({key: lesson[key] for key in values_to_keep})`

2024-08-18 08:46 UTC, mixx3 commented on timetable/mymsuapi_fetch.py
> +    url = "https://api.test.my.msu.ru/gateway/public/api/v1/public_content/lessons"
вот это лучше вынести куда-нибудь наверх в константы 
типа
```python
API_URL = "https://api.test.my.msu.ru/gateway/public/api/v1/"
LESSONS_ROUTE = API_URL + "public_content/lessons"
...
```

2024-08-18 08:46 UTC, mixx3 commented on timetable/mymsuapi_fetch.py
> +        "retry_delay": timedelta(minutes=5)
вот здесь спорный момент
1) я бы оставил питоновский код только для хождения в апи и заливки в raw
2) я бы в ods делал flatten уже средствами постгреса, потому что так быстрее 
типа так https://dba.stackexchange.com/questions/125912/postgresql-flatten-json-array-data

2024-08-19 09:10 UTC, Zimovchik commented on timetable/mymsuapi_fetch.py
> +    values_to_keep = [
Этой функции тут вообще быть не должно :) я ее просто не убрал, потому что с нее писал свои таски

2024-08-24 08:27 UTC, Wudext requested changes

2024-08-24 08:27 UTC, Wudext commented on timetable/mymsuapi_fetch.py
> +#     get_timetable_for_semester_to_db() >> flatten_timetable()
Снеси комменты все если они не нужны

2024-08-24 08:27 UTC, Wudext commented on timetable/mymsuapi_fetch.py
> +            if response.status_code == 200:
Я бы сюда добавил что-то в духе
` logging.info(
                "Successfully fetched cource %d flow %d timetable",
                source[0],
                source[1],
            )`

2024-08-24 08:27 UTC, Wudext commented on timetable/mymsuapi_fetch.py
> +                "Course %d flow %d timetable fetched with status %d",
А вот это бы снес, т.к. не особо несет в себе смысла

2024-08-24 08:28 UTC, Wudext commented
Сделай пулл в ветке заодно

2024-08-27 15:38 UTC, Zimovchik commented
@mixx3 Оно вроде как умеет более менее адекватно забрать расписание в stg-шку, теперь мне надо пофиксить траблы с flattening-ом

2024-08-27 15:43 UTC, Zimovchik commented
![изображение](https://github.com/user-attachments/assets/01f836a7-c298-4b76-ad1d-bf60e639aa81)
Забирает расписание, если что-то не заполнено то оно скипает.
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "ods_mymsuapi.ods_timetable_api_flattened" does not exist
LINE 2:         INSERT INTO ODS_MYMSUAPI.ods_timetable_api_flattened...
```
Эта ошибка появляется на таске flattening-га, судя по всему какая-то ошибка в sql запросе, пока не разобрался еще.
Мб надо проверять перед запросом существование таблички и ес че ее создавать. Но вообще это странно

2024-08-27 18:35 UTC, mixx3 approved these changes

2024-08-27 18:35 UTC, merged